### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by Cellebyte**
Fix to use yaml.safe_load

### CODE REVIEW

**Comment by Cellebyte** [comment]
Please merge :)

**Comment by coldnight** [comment]
Thanks

**Comment by Cellebyte** [comment]
Can you release 0.0.6?

**Comment by coldnight** [comment]
0.0.6 has released.

**Comment by Cellebyte** [comment]
Nice thank you, I will update tomorrow.
A colleague of mine had the nice idea of supporting a framework and programming language independent server mock solution for REST APIs. Will invest some Time into that.

**Pull request merged**
